#############################################################################
# Makefile for building: StdpC
# Generated by qmake (2.01a) (Qt 4.5.0) on: Fri 18. Dec 19:23:36 2009
# Project:  StdpC.pro
# Template: app
# Command: c:\Qt\4.5.0\bin\qmake -win32 -o Makefile StdpC.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DUNICODE -DQT_LARGEFILE_SUPPORT -DQT_THREAD_SUPPORT -DQT_DLL -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN
CFLAGS        = -O2 -Wall $(DEFINES)
CXXFLAGS      = -O2 -frtti -fexceptions -mthreads -Wall $(DEFINES)
INCPATH       = -I"c:\Qt\4.5.0\include\QtCore" -I"c:\Qt\4.5.0\include\QtGui" -I"c:\Qt\4.5.0\include" -I"." -I"src" -I"src\core" -I"src\drivers" -I"src\gui" -I"src\models" -I"src\nidaqmx" -I"src\include" -I"lib" -I"c:\Program Files\National Instruments\NI-DAQ\DAQmx ANSI C Dev\include" -I"c:\Qt\4.5.0\include\ActiveQt" -I"build" -I"src\gui\ui" -I"c:\Qt\4.5.0\mkspecs\default"
LINK        =        g++
LFLAGS        =        -enable-stdcall-fixup -Wl,-enable-auto-import -Wl,-enable-runtime-pseudo-reloc -Wl,-s -mthreads -Wl -Wl,-subsystem,windows
LIBS        =        -L"c:\Qt\4.5.0\lib" -lmingw32 -lqtmain staticlib/pt_ioctl_tn.a -lQtGui4 -lQtCore4
QMAKE         = c:\Qt\4.5.0\bin\qmake
IDC           = c:\Qt\4.5.0\bin\idc.exe
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
DEL_FILE      = del
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
INSTALL_FILE    = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR     = $(COPY_DIR)

####### Output directory

OBJECTS_DIR   = build

####### Files

SOURCES       = src\core\main.cpp \
		src\gui\mainwin.cpp \
		src\gui\ChemSynDlg.cpp \
		src\gui\GapJunctionDlg.cpp \
		src\gui\HHDlg.cpp \
		src\gui\AlphaBetaHHDlg.cpp \
		src\core\DCThread.cpp \
		src\gui\STDPDlg.cpp \
		src\gui\ODESTDPDlg.cpp \
		src\gui\SpikeTimeDlg.cpp \
		src\core\LUtables.cpp \
		src\gui\InputChannelDlg.cpp \
		src\core\global.cpp \
		src\core\global_func.cpp \
		src\gui\OutputChannelDlg.cpp \
		src\drivers\DigiData.cpp \
		src\core\Channels.cpp \
		src\gui\SimulDAQDlg.cpp \
		src\gui\DigiDataDlg.cpp \
		src\models\ChemSyn.cpp \
		src\models\GapJunction.cpp \
		src\models\HH.cpp \
		src\models\abHH.cpp \
		src\drivers\DAQ.cpp \
		src\drivers\SimulDAQ.cpp \
		src\models\SpkGen.cpp \
		src\core\Graph.cpp \
		src\gui\GraphDlg.cpp \
		src\gui\DAQDlg.cpp \
		src\core\ObjectDataTypes.cpp \
		src\core\scripting.cpp \
		src\gui\abSynDlg.cpp \
		src\gui\MeasMethodDlg.cpp \
		src\models\abSyn.cpp \
		src\core\AECChannel.cpp build\moc_mainwin.cpp \
		build\moc_ChemSynDlg.cpp \
		build\moc_GapJunctionDlg.cpp \
		build\moc_HHDlg.cpp \
		build\moc_AlphaBetaHHDlg.cpp \
		build\moc_DCThread.cpp \
		build\moc_STDPDlg.cpp \
		build\moc_ODESTDPDlg.cpp \
		build\moc_SpikeTimeDlg.cpp \
		build\moc_InputChannelDlg.cpp \
		build\moc_OutputChannelDlg.cpp \
		build\moc_SimulDAQDlg.cpp \
		build\moc_DigiDataDlg.cpp \
		build\moc_SpkGen.cpp \
		build\moc_Graph.cpp \
		build\moc_GraphDlg.cpp \
		build\moc_DAQDlg.cpp \
		build\moc_abSynDlg.cpp \
		build\moc_MeasMethodDlg.cpp
OBJECTS       = build/main.o \
		build/mainwin.o \
		build/ChemSynDlg.o \
		build/GapJunctionDlg.o \
		build/HHDlg.o \
		build/AlphaBetaHHDlg.o \
		build/DCThread.o \
		build/STDPDlg.o \
		build/ODESTDPDlg.o \
		build/SpikeTimeDlg.o \
		build/LUtables.o \
		build/InputChannelDlg.o \
		build/global.o \
		build/global_func.o \
		build/OutputChannelDlg.o \
		build/DigiData.o \
		build/Channels.o \
		build/SimulDAQDlg.o \
		build/DigiDataDlg.o \
		build/ChemSyn.o \
		build/GapJunction.o \
		build/HH.o \
		build/abHH.o \
		build/DAQ.o \
		build/SimulDAQ.o \
		build/SpkGen.o \
		build/Graph.o \
		build/GraphDlg.o \
		build/DAQDlg.o \
		build/ObjectDataTypes.o \
		build/scripting.o \
		build/abSynDlg.o \
		build/MeasMethodDlg.o \
		build/abSyn.o \
		build/AECChannel.o \
		build/moc_mainwin.o \
		build/moc_ChemSynDlg.o \
		build/moc_GapJunctionDlg.o \
		build/moc_HHDlg.o \
		build/moc_AlphaBetaHHDlg.o \
		build/moc_DCThread.o \
		build/moc_STDPDlg.o \
		build/moc_ODESTDPDlg.o \
		build/moc_SpikeTimeDlg.o \
		build/moc_InputChannelDlg.o \
		build/moc_OutputChannelDlg.o \
		build/moc_SimulDAQDlg.o \
		build/moc_DigiDataDlg.o \
		build/moc_SpkGen.o \
		build/moc_Graph.o \
		build/moc_GraphDlg.o \
		build/moc_DAQDlg.o \
		build/moc_abSynDlg.o \
		build/moc_MeasMethodDlg.o
DIST          = 
QMAKE_TARGET  = StdpC
DESTDIR        =  #avoid trailing-slash linebreak
TARGET         = StdpC.exe
DESTDIR_TARGET = StdpC.exe

####### Implicit rules

.SUFFIXES: .cpp .cc .cxx .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

first: all
all: Makefile  $(DESTDIR_TARGET)

$(DESTDIR_TARGET): src/gui/ui/ui_mainwin.h src/gui/ui/ui_ChemSynDlg.h src/gui/ui/ui_GapJunctionDlg.h src/gui/ui/ui_STDPDlg.h src/gui/ui/ui_ODESTDPDlg.h src/gui/ui/ui_SpikeTimeDlg.h src/gui/ui/ui_InputChannelDlg.h src/gui/ui/ui_GraphDlg.h src/gui/ui/ui_HHDlg.h src/gui/ui/ui_AlphaBetaHHDlg.h src/gui/ui/ui_OutputChannelDlg.h src/gui/ui/ui_SimulDAQDlg.h src/gui/ui/ui_DigiDataDlg.h src/gui/ui/ui_NIDAQDlg.h src/gui/ui/ui_abSynDlg.h src/gui/ui/ui_MeasMethodDlg.h $(OBJECTS) 
	$(LINK) $(LFLAGS) -o $(DESTDIR_TARGET) object_script.StdpC  $(LIBS)


Makefile: StdpC.pro  c:/Qt/4.5.0/mkspecs/default/qmake.conf c:/Qt/4.5.0/mkspecs/qconfig.pri \
		c:/Qt/4.5.0/mkspecs/features/qt_functions.prf \
		c:/Qt/4.5.0/mkspecs/features/qt_config.prf \
		c:/Qt/4.5.0/mkspecs/features/exclusive_builds.prf \
		c:/Qt/4.5.0/mkspecs/features/default_pre.prf \
		c:/Qt/4.5.0/mkspecs/features/win32/default_pre.prf \
		c:/Qt/4.5.0/mkspecs/features/release.prf \
		c:/Qt/4.5.0/mkspecs/features/default_post.prf \
		c:/Qt/4.5.0/mkspecs/features/win32/default_post.prf \
		c:/Qt/4.5.0/mkspecs/features/win32/thread.prf \
		c:/Qt/4.5.0/mkspecs/features/qt.prf \
		c:/Qt/4.5.0/mkspecs/features/moc.prf \
		c:/Qt/4.5.0/mkspecs/features/win32/rtti.prf \
		c:/Qt/4.5.0/mkspecs/features/win32/exceptions.prf \
		c:/Qt/4.5.0/mkspecs/features/win32/stl.prf \
		c:/Qt/4.5.0/mkspecs/features/shared.prf \
		c:/Qt/4.5.0/mkspecs/features/warn_on.prf \
		c:/Qt/4.5.0/mkspecs/features/win32/windows.prf \
		c:/Qt/4.5.0/mkspecs/features/resources.prf \
		c:/Qt/4.5.0/mkspecs/features/uic.prf \
		c:/Qt/4.5.0/mkspecs/features/yacc.prf \
		c:/Qt/4.5.0/mkspecs/features/lex.prf \
		c:/Qt/4.5.0/lib/qtmain.prl
	$(QMAKE) -win32 -o Makefile StdpC.pro
c:\Qt\4.5.0\mkspecs\qconfig.pri:
c:\Qt\4.5.0\mkspecs\features\qt_functions.prf:
c:\Qt\4.5.0\mkspecs\features\qt_config.prf:
c:\Qt\4.5.0\mkspecs\features\exclusive_builds.prf:
c:\Qt\4.5.0\mkspecs\features\default_pre.prf:
c:\Qt\4.5.0\mkspecs\features\win32\default_pre.prf:
c:\Qt\4.5.0\mkspecs\features\release.prf:
c:\Qt\4.5.0\mkspecs\features\default_post.prf:
c:\Qt\4.5.0\mkspecs\features\win32\default_post.prf:
c:\Qt\4.5.0\mkspecs\features\win32\thread.prf:
c:\Qt\4.5.0\mkspecs\features\qt.prf:
c:\Qt\4.5.0\mkspecs\features\moc.prf:
c:\Qt\4.5.0\mkspecs\features\win32\rtti.prf:
c:\Qt\4.5.0\mkspecs\features\win32\exceptions.prf:
c:\Qt\4.5.0\mkspecs\features\win32\stl.prf:
c:\Qt\4.5.0\mkspecs\features\shared.prf:
c:\Qt\4.5.0\mkspecs\features\warn_on.prf:
c:\Qt\4.5.0\mkspecs\features\win32\windows.prf:
c:\Qt\4.5.0\mkspecs\features\resources.prf:
c:\Qt\4.5.0\mkspecs\features\uic.prf:
c:\Qt\4.5.0\mkspecs\features\yacc.prf:
c:\Qt\4.5.0\mkspecs\features\lex.prf:
c:\Qt\4.5.0\lib\qtmain.prl:
qmake:  FORCE
	@$(QMAKE) -win32 -o Makefile StdpC.pro

dist:
	$(ZIP) StdpC.zip $(SOURCES) $(DIST) StdpC.pro c:\Qt\4.5.0\mkspecs\qconfig.pri c:\Qt\4.5.0\mkspecs\features\qt_functions.prf c:\Qt\4.5.0\mkspecs\features\qt_config.prf c:\Qt\4.5.0\mkspecs\features\exclusive_builds.prf c:\Qt\4.5.0\mkspecs\features\default_pre.prf c:\Qt\4.5.0\mkspecs\features\win32\default_pre.prf c:\Qt\4.5.0\mkspecs\features\release.prf c:\Qt\4.5.0\mkspecs\features\default_post.prf c:\Qt\4.5.0\mkspecs\features\win32\default_post.prf c:\Qt\4.5.0\mkspecs\features\win32\thread.prf c:\Qt\4.5.0\mkspecs\features\qt.prf c:\Qt\4.5.0\mkspecs\features\moc.prf c:\Qt\4.5.0\mkspecs\features\win32\rtti.prf c:\Qt\4.5.0\mkspecs\features\win32\exceptions.prf c:\Qt\4.5.0\mkspecs\features\win32\stl.prf c:\Qt\4.5.0\mkspecs\features\shared.prf c:\Qt\4.5.0\mkspecs\features\warn_on.prf c:\Qt\4.5.0\mkspecs\features\win32\windows.prf c:\Qt\4.5.0\mkspecs\features\resources.prf c:\Qt\4.5.0\mkspecs\features\uic.prf c:\Qt\4.5.0\mkspecs\features\yacc.prf c:\Qt\4.5.0\mkspecs\features\lex.prf c:\Qt\4.5.0\lib\qtmain.prl  HEADERS RESOURCES IMAGES SOURCES OBJECTIVE_SOURCES FORMS YACCSOURCES YACCSOURCES LEXSOURCES 

clean: compiler_clean 
	-$(DEL_FILE) build\main.o build\mainwin.o build\ChemSynDlg.o build\GapJunctionDlg.o build\HHDlg.o build\AlphaBetaHHDlg.o build\DCThread.o build\STDPDlg.o build\ODESTDPDlg.o build\SpikeTimeDlg.o build\LUtables.o build\InputChannelDlg.o build\global.o build\global_func.o build\OutputChannelDlg.o build\DigiData.o build\Channels.o build\SimulDAQDlg.o build\DigiDataDlg.o build\ChemSyn.o build\GapJunction.o build\HH.o build\abHH.o build\DAQ.o build\SimulDAQ.o build\SpkGen.o build\Graph.o build\GraphDlg.o build\DAQDlg.o build\ObjectDataTypes.o build\scripting.o build\abSynDlg.o build\MeasMethodDlg.o build\abSyn.o build\AECChannel.o build\moc_mainwin.o build\moc_ChemSynDlg.o build\moc_GapJunctionDlg.o build\moc_HHDlg.o build\moc_AlphaBetaHHDlg.o build\moc_DCThread.o build\moc_STDPDlg.o build\moc_ODESTDPDlg.o build\moc_SpikeTimeDlg.o build\moc_InputChannelDlg.o build\moc_OutputChannelDlg.o build\moc_SimulDAQDlg.o build\moc_DigiDataDlg.o build\moc_SpkGen.o build\moc_Graph.o build\moc_GraphDlg.o build\moc_DAQDlg.o build\moc_abSynDlg.o build\moc_MeasMethodDlg.o

distclean: clean
	-$(DEL_FILE) $(DESTDIR_TARGET)
	-$(DEL_FILE) Makefile

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_mainwin.cpp build/moc_ChemSynDlg.cpp build/moc_GapJunctionDlg.cpp build/moc_HHDlg.cpp build/moc_AlphaBetaHHDlg.cpp build/moc_DCThread.cpp build/moc_STDPDlg.cpp build/moc_ODESTDPDlg.cpp build/moc_SpikeTimeDlg.cpp build/moc_InputChannelDlg.cpp build/moc_OutputChannelDlg.cpp build/moc_SimulDAQDlg.cpp build/moc_DigiDataDlg.cpp build/moc_SpkGen.cpp build/moc_Graph.cpp build/moc_GraphDlg.cpp build/moc_DAQDlg.cpp build/moc_abSynDlg.cpp build/moc_MeasMethodDlg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build\moc_mainwin.cpp build\moc_ChemSynDlg.cpp build\moc_GapJunctionDlg.cpp build\moc_HHDlg.cpp build\moc_AlphaBetaHHDlg.cpp build\moc_DCThread.cpp build\moc_STDPDlg.cpp build\moc_ODESTDPDlg.cpp build\moc_SpikeTimeDlg.cpp build\moc_InputChannelDlg.cpp build\moc_OutputChannelDlg.cpp build\moc_SimulDAQDlg.cpp build\moc_DigiDataDlg.cpp build\moc_SpkGen.cpp build\moc_Graph.cpp build\moc_GraphDlg.cpp build\moc_DAQDlg.cpp build\moc_abSynDlg.cpp build\moc_MeasMethodDlg.cpp
build/moc_mainwin.cpp: src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h \
		src/gui/ui/ui_mainwin.h \
		src/include/InputChannelDlg.h \
		src/gui/ui/ui_InputChannelDlg.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/DAQ.h \
		src/include/OutputChannelDlg.h \
		src/include/ChemSynDlg.h \
		src/gui/ui/ui_ChemSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/abSynDlg.h \
		src/gui/ui/ui_abSynDlg.h \
		src/include/GapJunctionDlg.h \
		src/gui/ui/ui_GapJunctionDlg.h \
		src/include/HHDlg.h \
		src/gui/ui/ui_HHDlg.h \
		src/include/AlphaBetaHHDlg.h \
		src/gui/ui/ui_AlphaBetaHHDlg.h \
		src/include/SpikeTimeDlg.h \
		src/gui/ui/ui_SpikeTimeDlg.h \
		src/include/mainwin.h \
		src/include/DigiDataDlg.h \
		src/gui/ui/ui_DigiDataDlg.h \
		src/include/DAQDlg.h \
		src/include/SimulDAQDlg.h \
		src/gui/ui/ui_SimulDAQDlg.h \
		src/include/MeasMethodDlg.h \
		src/gui/ui/ui_MeasMethodDlg.h \
		src/include/DCThread.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/NIDAQDlg.h \
		src/gui/ui/ui_NIDAQDlg.h \
		src/include/SimulDAQ.h \
		src/include/NIDAQ.h \
		src/include/Graph.h \
		src/include/GraphDlg.h \
		src/gui/ui/ui_GraphDlg.h \
		src/include/mainwin.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\mainwin.h -o build\moc_mainwin.cpp

build/moc_ChemSynDlg.cpp: src/gui/ui/ui_ChemSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/ChemSynDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\ChemSynDlg.h -o build\moc_ChemSynDlg.cpp

build/moc_GapJunctionDlg.cpp: src/gui/ui/ui_GapJunctionDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/GapJunctionDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\GapJunctionDlg.h -o build\moc_GapJunctionDlg.cpp

build/moc_HHDlg.cpp: src/gui/ui/ui_HHDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/HHDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\HHDlg.h -o build\moc_HHDlg.cpp

build/moc_AlphaBetaHHDlg.cpp: src/gui/ui/ui_AlphaBetaHHDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/AlphaBetaHHDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\AlphaBetaHHDlg.h -o build\moc_AlphaBetaHHDlg.cpp

build/moc_DCThread.cpp: src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/Channels.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/DAQ.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/DCThread.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\DCThread.h -o build\moc_DCThread.cpp

build/moc_STDPDlg.cpp: src/gui/ui/ui_STDPDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/STDPDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\STDPDlg.h -o build\moc_STDPDlg.cpp

build/moc_ODESTDPDlg.cpp: src/gui/ui/ui_ODESTDPDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/ODESTDPDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\ODESTDPDlg.h -o build\moc_ODESTDPDlg.cpp

build/moc_SpikeTimeDlg.cpp: src/gui/ui/ui_SpikeTimeDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/mainwin.h \
		src/gui/ui/ui_mainwin.h \
		src/include/InputChannelDlg.h \
		src/gui/ui/ui_InputChannelDlg.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/DAQ.h \
		src/include/OutputChannelDlg.h \
		src/include/ChemSynDlg.h \
		src/gui/ui/ui_ChemSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/abSynDlg.h \
		src/gui/ui/ui_abSynDlg.h \
		src/include/GapJunctionDlg.h \
		src/gui/ui/ui_GapJunctionDlg.h \
		src/include/HHDlg.h \
		src/gui/ui/ui_HHDlg.h \
		src/include/AlphaBetaHHDlg.h \
		src/gui/ui/ui_AlphaBetaHHDlg.h \
		src/include/SpikeTimeDlg.h \
		src/include/DigiDataDlg.h \
		src/gui/ui/ui_DigiDataDlg.h \
		src/include/DAQDlg.h \
		src/include/SimulDAQDlg.h \
		src/gui/ui/ui_SimulDAQDlg.h \
		src/include/MeasMethodDlg.h \
		src/gui/ui/ui_MeasMethodDlg.h \
		src/include/DCThread.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/NIDAQDlg.h \
		src/gui/ui/ui_NIDAQDlg.h \
		src/include/SimulDAQ.h \
		src/include/NIDAQ.h \
		src/include/Graph.h \
		src/include/GraphDlg.h \
		src/gui/ui/ui_GraphDlg.h \
		src/include/SpikeTimeDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\SpikeTimeDlg.h -o build\moc_SpikeTimeDlg.cpp

build/moc_InputChannelDlg.cpp: src/gui/ui/ui_InputChannelDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/DAQ.h \
		src/include/InputChannelDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\InputChannelDlg.h -o build\moc_InputChannelDlg.cpp

build/moc_OutputChannelDlg.cpp: src/include/ObjectDataTypes.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/DAQ.h \
		src/include/OutputChannelDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\OutputChannelDlg.h -o build\moc_OutputChannelDlg.cpp

build/moc_SimulDAQDlg.cpp: src/gui/ui/ui_SimulDAQDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DAQDlg.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/SimulDAQDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\SimulDAQDlg.h -o build\moc_SimulDAQDlg.cpp

build/moc_DigiDataDlg.cpp: src/gui/ui/ui_DigiDataDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DAQDlg.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/DigiDataDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\DigiDataDlg.h -o build\moc_DigiDataDlg.cpp

build/moc_SpkGen.cpp: src/include/global_func.h \
		src/include/LUtables.h \
		src/include/ObjectDataTypes.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/SpkGen.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\SpkGen.h -o build\moc_SpkGen.cpp

build/moc_Graph.cpp: src/include/ObjectDataTypes.h \
		src/include/Graph.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\Graph.h -o build\moc_Graph.cpp

build/moc_GraphDlg.cpp: src/gui/ui/ui_GraphDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/GraphDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\GraphDlg.h -o build\moc_GraphDlg.cpp

build/moc_DAQDlg.cpp: src/include/DAQDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\DAQDlg.h -o build\moc_DAQDlg.cpp

build/moc_abSynDlg.cpp: src/gui/ui/ui_abSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/abSynDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\abSynDlg.h -o build\moc_abSynDlg.cpp

build/moc_MeasMethodDlg.cpp: src/gui/ui/ui_MeasMethodDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DCThread.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/Channels.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/DAQ.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/MeasMethodDlg.h
	C:\Qt\4.5.0\bin\moc.exe $(DEFINES) $(INCPATH) -D__GNUC__ -DWIN32 src\include\MeasMethodDlg.h -o build\moc_MeasMethodDlg.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/gui/ui/ui_mainwin.h src/gui/ui/ui_ChemSynDlg.h src/gui/ui/ui_GapJunctionDlg.h src/gui/ui/ui_STDPDlg.h src/gui/ui/ui_ODESTDPDlg.h src/gui/ui/ui_SpikeTimeDlg.h src/gui/ui/ui_InputChannelDlg.h src/gui/ui/ui_GraphDlg.h src/gui/ui/ui_HHDlg.h src/gui/ui/ui_AlphaBetaHHDlg.h src/gui/ui/ui_OutputChannelDlg.h src/gui/ui/ui_SimulDAQDlg.h src/gui/ui/ui_DigiDataDlg.h src/gui/ui/ui_NIDAQDlg.h src/gui/ui/ui_abSynDlg.h src/gui/ui/ui_MeasMethodDlg.h
compiler_uic_clean:
	-$(DEL_FILE) src\gui\ui\ui_mainwin.h src\gui\ui\ui_ChemSynDlg.h src\gui\ui\ui_GapJunctionDlg.h src\gui\ui\ui_STDPDlg.h src\gui\ui\ui_ODESTDPDlg.h src\gui\ui\ui_SpikeTimeDlg.h src\gui\ui\ui_InputChannelDlg.h src\gui\ui\ui_GraphDlg.h src\gui\ui\ui_HHDlg.h src\gui\ui\ui_AlphaBetaHHDlg.h src\gui\ui\ui_OutputChannelDlg.h src\gui\ui\ui_SimulDAQDlg.h src\gui\ui\ui_DigiDataDlg.h src\gui\ui\ui_NIDAQDlg.h src\gui\ui\ui_abSynDlg.h src\gui\ui\ui_MeasMethodDlg.h
src/gui/ui/ui_mainwin.h: src/gui/mainwin.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\mainwin.ui -o src\gui\ui\ui_mainwin.h

src/gui/ui/ui_ChemSynDlg.h: src/gui/ChemSynDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\ChemSynDlg.ui -o src\gui\ui\ui_ChemSynDlg.h

src/gui/ui/ui_GapJunctionDlg.h: src/gui/GapJunctionDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\GapJunctionDlg.ui -o src\gui\ui\ui_GapJunctionDlg.h

src/gui/ui/ui_STDPDlg.h: src/gui/STDPDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\STDPDlg.ui -o src\gui\ui\ui_STDPDlg.h

src/gui/ui/ui_ODESTDPDlg.h: src/gui/ODESTDPDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\ODESTDPDlg.ui -o src\gui\ui\ui_ODESTDPDlg.h

src/gui/ui/ui_SpikeTimeDlg.h: src/gui/SpikeTimeDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\SpikeTimeDlg.ui -o src\gui\ui\ui_SpikeTimeDlg.h

src/gui/ui/ui_InputChannelDlg.h: src/gui/InputChannelDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\InputChannelDlg.ui -o src\gui\ui\ui_InputChannelDlg.h

src/gui/ui/ui_GraphDlg.h: src/gui/GraphDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\GraphDlg.ui -o src\gui\ui\ui_GraphDlg.h

src/gui/ui/ui_HHDlg.h: src/gui/HHDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\HHDlg.ui -o src\gui\ui\ui_HHDlg.h

src/gui/ui/ui_AlphaBetaHHDlg.h: src/gui/AlphaBetaHHDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\AlphaBetaHHDlg.ui -o src\gui\ui\ui_AlphaBetaHHDlg.h

src/gui/ui/ui_OutputChannelDlg.h: src/gui/OutputChannelDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\OutputChannelDlg.ui -o src\gui\ui\ui_OutputChannelDlg.h

src/gui/ui/ui_SimulDAQDlg.h: src/gui/SimulDAQDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\SimulDAQDlg.ui -o src\gui\ui\ui_SimulDAQDlg.h

src/gui/ui/ui_DigiDataDlg.h: src/gui/DigiDataDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\DigiDataDlg.ui -o src\gui\ui\ui_DigiDataDlg.h

src/gui/ui/ui_NIDAQDlg.h: src/gui/NIDAQDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\NIDAQDlg.ui -o src\gui\ui\ui_NIDAQDlg.h

src/gui/ui/ui_abSynDlg.h: src/gui/abSynDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\abSynDlg.ui -o src\gui\ui\ui_abSynDlg.h

src/gui/ui/ui_MeasMethodDlg.h: src/gui/MeasMethodDlg.ui
	c:\Qt\4.5.0\bin\uic.exe src\gui\MeasMethodDlg.ui -o src\gui\ui\ui_MeasMethodDlg.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 



####### Compile

build/main.o: src/core/main.cpp src/include/main.h \
		src/include/mainwin.h \
		src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h \
		src/gui/ui/ui_mainwin.h \
		src/include/InputChannelDlg.h \
		src/gui/ui/ui_InputChannelDlg.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/DAQ.h \
		src/include/OutputChannelDlg.h \
		src/include/ChemSynDlg.h \
		src/gui/ui/ui_ChemSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/abSynDlg.h \
		src/gui/ui/ui_abSynDlg.h \
		src/include/GapJunctionDlg.h \
		src/gui/ui/ui_GapJunctionDlg.h \
		src/include/HHDlg.h \
		src/gui/ui/ui_HHDlg.h \
		src/include/AlphaBetaHHDlg.h \
		src/gui/ui/ui_AlphaBetaHHDlg.h \
		src/include/SpikeTimeDlg.h \
		src/gui/ui/ui_SpikeTimeDlg.h \
		src/include/DigiDataDlg.h \
		src/gui/ui/ui_DigiDataDlg.h \
		src/include/DAQDlg.h \
		src/include/SimulDAQDlg.h \
		src/gui/ui/ui_SimulDAQDlg.h \
		src/include/MeasMethodDlg.h \
		src/gui/ui/ui_MeasMethodDlg.h \
		src/include/DCThread.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/NIDAQDlg.h \
		src/gui/ui/ui_NIDAQDlg.h \
		src/include/SimulDAQ.h \
		src/include/NIDAQ.h \
		src/include/Graph.h \
		src/include/GraphDlg.h \
		src/gui/ui/ui_GraphDlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\main.o src\core\main.cpp

build/mainwin.o: src/gui/mainwin.cpp src/include/mainwin.h \
		src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h \
		src/gui/ui/ui_mainwin.h \
		src/include/InputChannelDlg.h \
		src/gui/ui/ui_InputChannelDlg.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/DAQ.h \
		src/include/OutputChannelDlg.h \
		src/include/ChemSynDlg.h \
		src/gui/ui/ui_ChemSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/abSynDlg.h \
		src/gui/ui/ui_abSynDlg.h \
		src/include/GapJunctionDlg.h \
		src/gui/ui/ui_GapJunctionDlg.h \
		src/include/HHDlg.h \
		src/gui/ui/ui_HHDlg.h \
		src/include/AlphaBetaHHDlg.h \
		src/gui/ui/ui_AlphaBetaHHDlg.h \
		src/include/SpikeTimeDlg.h \
		src/gui/ui/ui_SpikeTimeDlg.h \
		src/include/DigiDataDlg.h \
		src/gui/ui/ui_DigiDataDlg.h \
		src/include/DAQDlg.h \
		src/include/SimulDAQDlg.h \
		src/gui/ui/ui_SimulDAQDlg.h \
		src/include/MeasMethodDlg.h \
		src/gui/ui/ui_MeasMethodDlg.h \
		src/include/DCThread.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/NIDAQDlg.h \
		src/gui/ui/ui_NIDAQDlg.h \
		src/include/SimulDAQ.h \
		src/include/NIDAQ.h \
		src/include/Graph.h \
		src/include/GraphDlg.h \
		src/gui/ui/ui_GraphDlg.h \
		src/gui/SynXComboChanged.cc \
		src/gui/HHXComboChanged.cc \
		src/include/AP.cc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\mainwin.o src\gui\mainwin.cpp

build/ChemSynDlg.o: src/gui/ChemSynDlg.cpp src/include/ChemSynDlg.h \
		src/gui/ui/ui_ChemSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\ChemSynDlg.o src\gui\ChemSynDlg.cpp

build/GapJunctionDlg.o: src/gui/GapJunctionDlg.cpp src/include/GapJunctionDlg.h \
		src/gui/ui/ui_GapJunctionDlg.h \
		src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\GapJunctionDlg.o src\gui\GapJunctionDlg.cpp

build/HHDlg.o: src/gui/HHDlg.cpp src/include/HHDlg.h \
		src/gui/ui/ui_HHDlg.h \
		src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\HHDlg.o src\gui\HHDlg.cpp

build/AlphaBetaHHDlg.o: src/gui/AlphaBetaHHDlg.cpp src/include/AlphaBetaHHDlg.h \
		src/gui/ui/ui_AlphaBetaHHDlg.h \
		src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\AlphaBetaHHDlg.o src\gui\AlphaBetaHHDlg.cpp

build/DCThread.o: src/core/DCThread.cpp src/include/DCThread.h \
		src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/Channels.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/DAQ.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/AP.h \
		src/include/SimulDAQ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\DCThread.o src\core\DCThread.cpp

build/STDPDlg.o: src/gui/STDPDlg.cpp src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\STDPDlg.o src\gui\STDPDlg.cpp

build/ODESTDPDlg.o: src/gui/ODESTDPDlg.cpp src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\ODESTDPDlg.o src\gui\ODESTDPDlg.cpp

build/SpikeTimeDlg.o: src/gui/SpikeTimeDlg.cpp src/include/SpikeTimeDlg.h \
		src/gui/ui/ui_SpikeTimeDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/mainwin.h \
		src/gui/ui/ui_mainwin.h \
		src/include/InputChannelDlg.h \
		src/gui/ui/ui_InputChannelDlg.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/DAQ.h \
		src/include/OutputChannelDlg.h \
		src/include/ChemSynDlg.h \
		src/gui/ui/ui_ChemSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/abSynDlg.h \
		src/gui/ui/ui_abSynDlg.h \
		src/include/GapJunctionDlg.h \
		src/gui/ui/ui_GapJunctionDlg.h \
		src/include/HHDlg.h \
		src/gui/ui/ui_HHDlg.h \
		src/include/AlphaBetaHHDlg.h \
		src/gui/ui/ui_AlphaBetaHHDlg.h \
		src/include/DigiDataDlg.h \
		src/gui/ui/ui_DigiDataDlg.h \
		src/include/DAQDlg.h \
		src/include/SimulDAQDlg.h \
		src/gui/ui/ui_SimulDAQDlg.h \
		src/include/MeasMethodDlg.h \
		src/gui/ui/ui_MeasMethodDlg.h \
		src/include/DCThread.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/NIDAQDlg.h \
		src/gui/ui/ui_NIDAQDlg.h \
		src/include/SimulDAQ.h \
		src/include/NIDAQ.h \
		src/include/Graph.h \
		src/include/GraphDlg.h \
		src/gui/ui/ui_GraphDlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\SpikeTimeDlg.o src\gui\SpikeTimeDlg.cpp

build/LUtables.o: src/core/LUtables.cpp src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\LUtables.o src\core\LUtables.cpp

build/InputChannelDlg.o: src/gui/InputChannelDlg.cpp src/include/InputChannelDlg.h \
		src/gui/ui/ui_InputChannelDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/DAQ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\InputChannelDlg.o src\gui\InputChannelDlg.cpp

build/global.o: src/core/global.cpp src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\global.o src\core\global.cpp

build/global_func.o: src/core/global_func.cpp src/include/LUtables.h \
		src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\global_func.o src\core\global_func.cpp

build/OutputChannelDlg.o: src/gui/OutputChannelDlg.cpp src/include/OutputChannelDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/DAQ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\OutputChannelDlg.o src\gui\OutputChannelDlg.cpp

build/DigiData.o: src/drivers/DigiData.cpp src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h \
		src/include/DAQ.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\DigiData.o src\drivers\DigiData.cpp

build/Channels.o: src/core/Channels.cpp src/include/Channels.h \
		src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\Channels.o src\core\Channels.cpp

build/SimulDAQDlg.o: src/gui/SimulDAQDlg.cpp src/include/SimulDAQDlg.h \
		src/gui/ui/ui_SimulDAQDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DAQDlg.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/gui/tools.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\SimulDAQDlg.o src\gui\SimulDAQDlg.cpp

build/DigiDataDlg.o: src/gui/DigiDataDlg.cpp src/include/DigiDataDlg.h \
		src/gui/ui/ui_DigiDataDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DAQDlg.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/gui/tools.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\DigiDataDlg.o src\gui\DigiDataDlg.cpp

build/ChemSyn.o: src/models/ChemSyn.cpp src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/LUtables.h \
		src/include/ObjectDataTypes.h \
		src/include/Channels.h \
		src/include/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\ChemSyn.o src\models\ChemSyn.cpp

build/GapJunction.o: src/models/GapJunction.cpp src/include/GapJunction.h \
		src/include/global_func.h \
		src/include/LUtables.h \
		src/include/ObjectDataTypes.h \
		src/include/Channels.h \
		src/include/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\GapJunction.o src\models\GapJunction.cpp

build/HH.o: src/models/HH.cpp src/include/HH.h \
		src/include/ObjectDataTypes.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/global_func.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\HH.o src\models\HH.cpp

build/abHH.o: src/models/abHH.cpp src/include/abHH.h \
		src/include/ObjectDataTypes.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/global_func.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\abHH.o src\models\abHH.cpp

build/DAQ.o: src/drivers/DAQ.cpp src/include/DAQ.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\DAQ.o src\drivers\DAQ.cpp

build/SimulDAQ.o: src/drivers/SimulDAQ.cpp src/include/SimulDaq.h \
		src/include/DAQ.h \
		src/include/Channels.h \
		src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\SimulDAQ.o src\drivers\SimulDAQ.cpp

build/SpkGen.o: src/models/SpkGen.cpp src/include/SpkGen.h \
		src/include/global_func.h \
		src/include/LUtables.h \
		src/include/ObjectDataTypes.h \
		src/include/Channels.h \
		src/include/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\SpkGen.o src\models\SpkGen.cpp

build/Graph.o: src/core/Graph.cpp src/include/Graph.h \
		src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\Graph.o src\core\Graph.cpp

build/GraphDlg.o: src/gui/GraphDlg.cpp src/include/GraphDlg.h \
		src/gui/ui/ui_GraphDlg.h \
		src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\GraphDlg.o src\gui\GraphDlg.cpp

build/DAQDlg.o: src/gui/DAQDlg.cpp src/include/DAQDlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\DAQDlg.o src\gui\DAQDlg.cpp

build/ObjectDataTypes.o: src/core/ObjectDataTypes.cpp src/include/ObjectDataTypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\ObjectDataTypes.o src\core\ObjectDataTypes.cpp

build/scripting.o: src/core/scripting.cpp src/include/scripting.h \
		src/include/global.h \
		src/include/ObjectDataTypes.h \
		src/include/LUtables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\scripting.o src\core\scripting.cpp

build/abSynDlg.o: src/gui/abSynDlg.cpp src/include/abSynDlg.h \
		src/gui/ui/ui_abSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\abSynDlg.o src\gui\abSynDlg.cpp

build/MeasMethodDlg.o: src/gui/MeasMethodDlg.cpp src/include/MeasMethodDlg.h \
		src/gui/ui/ui_MeasMethodDlg.h \
		src/include/ObjectDataTypes.h \
		src/include/DCThread.h \
		src/include/global.h \
		src/include/LUtables.h \
		src/include/ChemSyn.h \
		src/include/global_func.h \
		src/include/Channels.h \
		src/include/abSyn.h \
		src/include/GapJunction.h \
		src/include/HH.h \
		src/include/abHH.h \
		src/include/SpkGen.h \
		src/include/DigiData.h \
		src/include/pt_ioctl_tn.h \
		src/include/PortTalkX_IOCTL.h \
		src/include/DAQ.h \
		src/include/scripting.h \
		src/include/AECChannel.h \
		src/include/mainwin.h \
		src/gui/ui/ui_mainwin.h \
		src/include/InputChannelDlg.h \
		src/gui/ui/ui_InputChannelDlg.h \
		src/include/OutputChannelDlg.h \
		src/include/ChemSynDlg.h \
		src/gui/ui/ui_ChemSynDlg.h \
		src/include/STDPDlg.h \
		src/gui/ui/ui_STDPDlg.h \
		src/include/ODESTDPDlg.h \
		src/gui/ui/ui_ODESTDPDlg.h \
		src/include/abSynDlg.h \
		src/gui/ui/ui_abSynDlg.h \
		src/include/GapJunctionDlg.h \
		src/gui/ui/ui_GapJunctionDlg.h \
		src/include/HHDlg.h \
		src/gui/ui/ui_HHDlg.h \
		src/include/AlphaBetaHHDlg.h \
		src/gui/ui/ui_AlphaBetaHHDlg.h \
		src/include/SpikeTimeDlg.h \
		src/gui/ui/ui_SpikeTimeDlg.h \
		src/include/DigiDataDlg.h \
		src/gui/ui/ui_DigiDataDlg.h \
		src/include/DAQDlg.h \
		src/include/SimulDAQDlg.h \
		src/gui/ui/ui_SimulDAQDlg.h \
		src/include/NIDAQDlg.h \
		src/gui/ui/ui_NIDAQDlg.h \
		src/include/SimulDAQ.h \
		src/include/NIDAQ.h \
		src/include/Graph.h \
		src/include/GraphDlg.h \
		src/gui/ui/ui_GraphDlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\MeasMethodDlg.o src\gui\MeasMethodDlg.cpp

build/abSyn.o: src/models/abSyn.cpp src/include/abSyn.h \
		src/include/global_func.h \
		src/include/LUtables.h \
		src/include/ObjectDataTypes.h \
		src/include/Channels.h \
		src/include/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\abSyn.o src\models\abSyn.cpp

build/AECChannel.o: src/core/AECChannel.cpp src/include/AECChannel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\AECChannel.o src\core\AECChannel.cpp

build/moc_mainwin.o: build/moc_mainwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_mainwin.o build\moc_mainwin.cpp

build/moc_ChemSynDlg.o: build/moc_ChemSynDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_ChemSynDlg.o build\moc_ChemSynDlg.cpp

build/moc_GapJunctionDlg.o: build/moc_GapJunctionDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_GapJunctionDlg.o build\moc_GapJunctionDlg.cpp

build/moc_HHDlg.o: build/moc_HHDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_HHDlg.o build\moc_HHDlg.cpp

build/moc_AlphaBetaHHDlg.o: build/moc_AlphaBetaHHDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_AlphaBetaHHDlg.o build\moc_AlphaBetaHHDlg.cpp

build/moc_DCThread.o: build/moc_DCThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_DCThread.o build\moc_DCThread.cpp

build/moc_STDPDlg.o: build/moc_STDPDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_STDPDlg.o build\moc_STDPDlg.cpp

build/moc_ODESTDPDlg.o: build/moc_ODESTDPDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_ODESTDPDlg.o build\moc_ODESTDPDlg.cpp

build/moc_SpikeTimeDlg.o: build/moc_SpikeTimeDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_SpikeTimeDlg.o build\moc_SpikeTimeDlg.cpp

build/moc_InputChannelDlg.o: build/moc_InputChannelDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_InputChannelDlg.o build\moc_InputChannelDlg.cpp

build/moc_OutputChannelDlg.o: build/moc_OutputChannelDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_OutputChannelDlg.o build\moc_OutputChannelDlg.cpp

build/moc_SimulDAQDlg.o: build/moc_SimulDAQDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_SimulDAQDlg.o build\moc_SimulDAQDlg.cpp

build/moc_DigiDataDlg.o: build/moc_DigiDataDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_DigiDataDlg.o build\moc_DigiDataDlg.cpp

build/moc_SpkGen.o: build/moc_SpkGen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_SpkGen.o build\moc_SpkGen.cpp

build/moc_Graph.o: build/moc_Graph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_Graph.o build\moc_Graph.cpp

build/moc_GraphDlg.o: build/moc_GraphDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_GraphDlg.o build\moc_GraphDlg.cpp

build/moc_DAQDlg.o: build/moc_DAQDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_DAQDlg.o build\moc_DAQDlg.cpp

build/moc_abSynDlg.o: build/moc_abSynDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_abSynDlg.o build\moc_abSynDlg.cpp

build/moc_MeasMethodDlg.o: build/moc_MeasMethodDlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build\moc_MeasMethodDlg.o build\moc_MeasMethodDlg.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

